version: "3.9"

services:
  api:
    build: .
    container_name: penguins_api
    ports:
      - "8080:8080"
    volumes:
      - ./app/logs:/app/app/logs
    environment:
      - PYTHONUNBUFFERED=1

